### ISSUE TITLE
Yaml: Tags support is not enabled. Enable the `Yaml::PARSE_CUSTOM_TAGS`

### ISSUE THREAD

**Issue by distantnative** [k-next/data#15]
When calling the `/api/blueprints/blog` API endpoint:

```
::1:50901 [200]: /api/blueprints/blog - Uncaught Symfony\Component\Yaml\Exception\ParseException: Tags support is not enabled. Enable the `Yaml::PARSE_CUSTOM_TAGS` flag to use "!=" at line 30 (near "operator: !="). in …/starterkit/kirby/vendor/symfony/yaml/Inline.php:690
Stack trace:
#0 …/starterkit/kirby/vendor/symfony/yaml/Inline.php(82): Symfony\Component\Yaml\Inline::parseTag('!=', 2, 0)
#1 …/starterkit/kirby/vendor/symfony/yaml/Parser.php(714): Symfony\Component\Yaml\Inline::parse('!=', 0, Array)
#2 …/starterkit/kirby/vendor/symfony/yaml/Parser.php(337): Symfony\Component\Yaml\Parser->parseValue('!=', 0, 'mapping')
#3 …/starterkit/kirby/vendor/symfony/yaml/Parser.php(465): Symfony\Component\Yaml\Parser->doParse('draft', 0)
#4 …/starterkit/kirby/vendor/symfony/yaml/Parser.php(181): Symfony\Component\Yaml\Parser->parseBlock(28, 'field: draft\nop in …/starterkit/kirby/vendor/symfony/yaml/Inline.php on line 690
```

**Comment by distantnative** [comment]
And when setting it, I get

```
Uninitialized string offset: 2 in …/starterkit/kirby/vendor/symfony/yaml/Inline.php on line 83
```
